### ISSUE TITLE
Concierge - Price List, Prices

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#12]
Let's update them to:

Website $999
Logo $499
Domain Registration $49 

And then break down the different hosting options with clean descriptions of each:

$19 basic
$29 business
$39 managed

**Comment by rodneystrong** [comment]
Wow.. we're gettin pricey...

**Comment by irms** [comment]
Our line is $7999. We're going to push that as much as we can :)

**Comment by irms** [comment]
While still providing value, of course. Nothing shiesty.

**Comment by rodneystrong** [comment]
Got all prices except monthly descriptions updated. 

Will work with @rcsargent for details on this.

**Comment by jonadesign** [comment]
Old price still on sign up form -->
<img width="669" alt="screen shot 2015-10-28 at 3 16 29 pm" src="https://cloud.githubusercontent.com/assets/7379059/10804853/00104c76-7d87-11e5-81c5-326fa187f1cc.png">

**Comment by irms** [comment]
I'll take care of this.

**Comment by rodneystrong** [comment]
When users click on the 'hellobar' at the top, the old price is still displayed on the next page. fixing now.

**Comment by rodneystrong** [comment]
Actually, I wasn't able to change this because the one-time fee value is controlled by a variable called $setup_fee. I can't find anywhere on index.php where that var is initialized with a value though. 
<img width="843" alt="screen shot 2015-11-09 at 4 35 47 pm" src="https://cloud.githubusercontent.com/assets/539962/11051007/13700810-8700-11e5-9d9d-df1e56328bbb.png">

I was able to change the price of the logo though. Back on you @irms

**Comment by irms** [comment]
There is a new issue for this #36

**Comment by rodneystrong** [comment]
crap my bad.
