### ISSUE TITLE
Get all of our logos

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/buildicus-op1#30]
Go through our google drive and get all the PNGs of our logos and a JPG of the bottom portion of the PDF style guide (the section where we show the logo in real life on billboards + business cards ,etc). 

Be sure to get the logo that the client chose. Make sure it's a PNG of just the logo. 

Put them all in this folder:
https://drive.google.com/drive/folders/0B88_mCI0OTGkQThnM25wbzNUeEk

due:
10-9-15    8p

**Comment by vanderbeam** [comment]
@rodneystrong The first couple didn't have logos and a few of them don't have the pdf style guides. Do you want me to just get what I can from each one?

**Comment by rodneystrong** [comment]
Get what you can, and for the ones that don't have PDF style guides, contact the original creator and have him/her create one, upload to the correct google drive, and then do what this gh issues asks. 
In fact, in addition to this, please document here which sites don't have logos and which logos don't have style guides created.

**Comment by vanderbeam** [comment]
@rodneystrong Check. On it.

**Comment by vanderbeam** [comment]
So very few of the websites have logos in their files. I have questions about others.
"Nothing" means no logo to work with. I realize some of the names don't go with the companies. I went with the name of the folder. 

ADA - No logo whatsoever
CVP - Needs a branding jpeg
Beth Bridges - Nothing. There's a logo concept but I even tried finding her website and I couldn't find anything
Buildicus - Do you want me to include Buildicus in this?
C Carter - Need a branding jpeg
Cenpac - All set
Codergirlz - I'm not sure if this is their official logo since it's just text and not live yet
Huntress CPA - We used their logo
Cupcake - Nothing
Daycare - Need a branding jpeg
Easton CAruther's - Nothing
FFHHT - Need a branding jpeg
Fresno Minfulness Walks - Nothing
FresYes - Nothing
House Psychiatric - Nothing
Jay Kelly - Nothing
Joshua Long - Nothing
Knot Away - Need a branding jpeg
Landscape - Nothing
Leta Hering Skincare - Need a branding jpeg
Mariachi Solista - Need a branding jpeg
Motor Cross - Need a branding jpeg
Nate Ruland - Nothing
National Adjusting - There are A TON of logos in this folder. I'm honestly not sure which was correct
One Woman Adventure - Need a branding jpeg
PDK - Nothing
Plano - Nothing
Plumbing - Nothing
Primex - Need a branding jpeg
Pumpking King - Need a branding jpeg
Screamers movie - No official logo, unless you mean the "SCREAMERS" text?
Sublime Time - Since they don't have a logo do you want me to use the text?
UCP - Need a branding jpeg
Vintage Cars - Nothing
Wise Scuba - All set
Woodcraft - I don't know which logo actually got chosen. 

Let me know if this was what you had in mind.

**Comment by rodneystrong** [comment]
Good stuff, this is exactly what I asked for.
