### ISSUE TITLE
Concierge - Get Started Button

### ISSUE THREAD

**Issue by irms** [EditLLC/buildicus-op1#6]
Button is just not noticeable enough. 

<img width="301" alt="screenshot 2015-10-04 17 31 13" src="https://cloud.githubusercontent.com/assets/643997/10271236/c70f0a56-6abd-11e5-98ce-e0579bd08ac0.png">

Might I suggest a HelloBar at the top instead? One that remains static.

**Comment by rodneystrong** [comment]
I think i can code this myself actually. The hellobar is just a div that gets that i can .toggle() on. 

Notes for myself:
- use a setTimeOut parameter to true after 3000 
- make the div position: fixed but pushes content down instead of covering it
- http://api.jquery.com/toggle/
- maybe add a button that allows a user to toggle the hellobar manually

**Comment by irms** [comment]
I'm ok using the actual hellobar service. (free version). Your call.

**Comment by rodneystrong** [comment]
shit i am too then, let's do it (didn't know they went free)

**Comment by rodneystrong** [comment]
got the snippet:

````<script src="//my.hellobar.com/c947185e4ef2584060ce5730fcc842cf5280559d.js" type="text/javascript" charset="utf-8" async="async"></script>````

**Comment by rodneystrong** [comment]
pushed dd22473f089383660bc32251408ce08394f85577  and tested on http://buildicus.com/concierge/

added irma@buildicus.com as an admin for the hellobar account (it wouldn't let me make you owner yet, will try again)
